#obj-$(CONFIG_INTEL_QUARK_PLATFORM_GALILEO)	+= intel_quark_platform_galileo.o
obj-$(CONFIG_X86_INTEL_QUARK)			+= intel_quark_board_data.o
obj-$(CONFIG_X86_INTEL_QUARK)			+= intel_quark_platform_galileo_gen2.o
obj-$(CONFIG_X86_INTEL_QUARK)			+= intel_quark_platform_galileo.o
#obj-$(CONFIG_X86_INTEL_QUARK)>-+= intel_qrk_plat_clanton_hill.o
#obj-$(CONFIG_X86_INTEL_QUARK)>-+= intel_qrk_plat_clanton_peak.o
#obj-$(CONFIG_X86_INTEL_QUARK)>-+= intel_qrk_plat_cross_hill.o
#obj-$(CONFIG_X86_INTEL_QUARK)>-+= intel_qrk_plat_kips_bay.o
